Additional UI Manipulation via RegEx
jenkinsci/mission-control-view-plugin pull request #4
Opened 2017-02-14 03:11 UTC by willdeberry

Create the ability to filter Build History and Job Status individually. This
allows the user to create different regexs for each column.

For Example:
* Use the build history as an overall timeline
* Filter the job statuses to your most important builds that should always be
green

2017-03-02 06:12 UTC, a-shevtsov requested changes
This is a not very common case to break backward compatibility. What I would do is to leave existing filter and apply it both build history and job statuses by default (as it is now) but add another checkbox ( 'Different regex for Build History' for example) for those who needs this option.

2017-03-02 06:16 UTC, a-shevtsov requested changes
Good option, just need to make one change (see the comment).

2017-03-02 06:16 UTC, a-shevtsov commented on src/main/java/tech/andrey/jenkins/missioncontrol/MissionControlView.java
> +            return 0;
Please replace this with a static array/dictionary with keys in lower or upper case and convert status to that case when retrieving sort order value.

2017-05-05 03:00 UTC, willdeberry commented
Anything else need to be adjusted? Let me know, thanks!

2017-05-30 12:54 UTC, willdeberry commented on src/main/java/tech/andrey/jenkins/missioncontrol/MissionControlView.java
> +            return 0;
Done

2017-05-31 08:31 UTC, a-shevtsov approved these changes

2017-05-31 08:33 UTC, merged

2017-05-31 08:34 UTC, a-shevtsov commented
Thanks for making these changes. I'm really sorry I could not review this earlier.